Repository usdigitalresponse/usdr-gost, pull requests merged in 2023-12, with the labels that each got.

#2227 Improve CI/CD automations
  .github/CODEOWNERS
  .github/next_release_version.bash
  .github/release-drafter.yml
  .github/release.yml
  .github/workflows/aws-auth.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-api.yml
  .github/workflows/build-website.yml
  .github/workflows/build.yml
  .github/workflows/ci.yaml
  .github/workflows/ci.yml
  .github/workflows/code-scanning.yml
  .github/workflows/dependabot-auto-approve.yml
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
  .github/workflows/pr-tidying.yml
  .github/workflows/publish-qa-results.yml
  .github/workflows/publish-terraform-plan.yml
  .github/workflows/qa.yml
  .github/workflows/release-drafter.yml
  .github/workflows/select-target-environment.yml
  .github/workflows/terraform-apply.yml
  .github/workflows/terraform-ci.yml
  .github/workflows/terraform-plan.yml
  .github/workflows/validate-deployment.yml
  CONTRIBUTING.md
  README.md
  docs/deployment.md
  docs/releasing.md
  packages/server/.nycrc
  terraform/main.tf
  terraform/modules/gost_website/storage.tf
  terraform/modules/gost_website/variables.tf
  terraform/prod.tfvars
  terraform/staging.tfvars
  terraform/variables.tf
Labels: documentation, enhancement, Infra

#2303 2218 remove old grants table implementation and feature flag
  packages/client/public/deploy-config.js
  packages/client/src/components/GrantsTable.vue
  packages/client/src/components/Layout.vue
  packages/client/src/helpers/featureFlags/index.js
  packages/client/src/router/index.js
  packages/client/src/views/Dashboard.vue
  packages/client/src/views/Grants.vue
  packages/client/src/views/MyGrants.vue
  terraform/sandbox.tfvars
  terraform/staging.tfvars
Labels: enhancement, Infra, terraform, javascript

#2325 feat: Automatically invalidate CDN cache after deployment
  .github/workflows/terraform-apply.yml
  terraform/outputs.tf
Labels: enhancement, Infra, terraform, github

#2281 2256 docs for arpa worker and queue
  docker-compose.yml
  docker/README.md
  localstack/entrypoint/init-aws.sh
  package.json
  packages/server/.env.example
  packages/server/package.json
Labels: documentation, Infra, javascript

#2301 feat: add breadcrumbs on my profile page
  packages/client/src/views/MyProfile.vue
Labels: enhancement, javascript

#2324 fix: #2218 Additional cleanup from removing useNewTable feature flag
  packages/client/src/components/GrantsTable.vue
  packages/client/src/components/GrantsTableNext.vue
  terraform/prod.tfvars
Labels: bug, enhancement, Infra, terraform, javascript

#2323 feat: configure Cloudfront to support SPA using history API
  packages/client/public/errors/403.html
  packages/client/public/errors/404.html
  terraform/modules/gost_website/cdn.tf
Labels: enhancement, Infra, terraform, javascript

#2274 fix: switch to use vue-select instead of Multiselect
  packages/client/src/assets/adjust-vue-select.css
  packages/client/src/components/Modals/GrantDetails.vue
  packages/client/src/components/Modals/SearchPanel.vue
  packages/client/src/main.js
Labels: bug, javascript

#2343 Add Datadog RUM to client (issue #2067)
  packages/client/package.json
  packages/client/src/arpa_reporter/main.js
  packages/client/src/main.js
  service.datadog.yaml
  terraform/main.tf
  terraform/modules/gost_api/gateway.tf
  terraform/modules/gost_website/runtime_config.tf
  terraform/modules/gost_website/tpl/deploy-config.js
  terraform/modules/gost_website/variables.tf
  terraform/prod.tfvars
  terraform/staging.tfvars
  terraform/variables.tf
  yarn.lock
Labels: enhancement, dependencies, Infra, terraform, javascript

#2344 fix: remove unnecessary JSON.parse() call in RUM config template
  terraform/modules/gost_website/tpl/deploy-config.js
Labels: bug, Infra, terraform, javascript, skip-changelog

#2267 feat: add category of funding activity as search field
  packages/client/src/components/Modals/GrantDetails.vue
  packages/client/src/components/Modals/SearchPanel.vue
  packages/client/src/helpers/filters.js
  packages/client/src/store/modules/grants.js
  packages/server/__tests__/api/grants.test.js
  packages/server/__tests__/db/db.test.js
  packages/server/__tests__/db/seeds/fixtures.js
  packages/server/__tests__/lib/grants-ingest.test.js
  packages/server/migrations/20231117213914_add_funding_category_column_to_grants.js
  packages/server/seeds/dev/ref/grants.js
  packages/server/src/configure.js
  packages/server/src/db/index.js
  packages/server/src/lib/fieldConfigs/fundingActivityCategories.js
  packages/server/src/lib/grants-ingest.js
  packages/server/src/routes/grants.js
  packages/server/src/routes/searchConfig.js
Labels: enhancement, javascript, database-changes

#2315 fix: #2302 - EC code 1.4 fixes for wording
  packages/server/src/arpa_reporter/lib/arpa-ec-codes.js
Labels: bug, javascript

#2333 fix: #2332 - fix audit report expenditures
  packages/server/__tests__/arpa_reporter/server/lib/audit-report.spec.js
  packages/server/src/arpa_reporter/lib/audit-report.js
Labels: bug, javascript

#2338 #2337: New feature flag for moving Grant Details from a modal to an independent page
  packages/client/public/deploy-config.js
  packages/client/src/components/GrantsTable.vue
  packages/client/src/components/Modals/GrantDetailsLegacy.vue
  packages/client/src/helpers/featureFlags/index.js
  packages/client/src/views/Dashboard.vue
  packages/client/src/views/GrantDetails.vue
  packages/client/src/views/RecentActivity.vue
  packages/client/src/views/UpcomingClosingDates.vue
  terraform/prod.tfvars
  terraform/sandbox.tfvars
  terraform/staging.tfvars
Labels: enhancement, Infra, terraform, javascript

#2359 fix: #1928 update button variants on Users page
  packages/client/src/views/Users.vue
Labels: bug, javascript

#2361 feat: add feature flag for category of funding activity search field
  packages/client/public/deploy-config.js
  packages/client/src/components/Modals/GrantDetailsLegacy.vue
  packages/client/src/components/Modals/SearchPanel.vue
  packages/client/src/helpers/featureFlags/index.js
  terraform/prod.tfvars
  terraform/sandbox.tfvars
  terraform/staging.tfvars
Labels: enhancement, Infra, terraform, javascript

#2378 Fix skipped CI reports
  .github/workflows/ci.yml
Labels: bug, github

#2386 fix: make new GrantDetails page a child of Layout
  packages/client/src/router/index.js
Labels: bug, javascript

#2342 feat: switch grant finder to use history API for client-side routing
  docs/development.md
  packages/client/package.json
  packages/client/src/components/Layout.vue
  packages/client/src/main.js
  packages/client/src/router/index.js
  packages/client/src/views/Dashboard.vue
  packages/client/src/views/MyProfile.vue
  packages/client/src/views/NotFound.vue
  packages/client/tests/unit/router/routes.spec.js
  packages/client/vue.config.js
  packages/server/__tests__/api/sessions.test.js
  packages/server/__tests__/lib/redirect_validation.test.js
  packages/server/src/lib/email.js
  packages/server/src/lib/redirect_validation.js
  packages/server/src/routes/sessions.js
  yarn.lock
Labels: documentation, enhancement, dependencies, javascript

#2360 fix: eliminate "property not defined on instance" error in Dashboard.vue
  packages/client/src/views/Dashboard.vue
Labels: bug, javascript

#2387 fix: #2312 agency Name not appearing on Recent Activity on Dashboard
  packages/client/src/views/Dashboard.vue
Labels: bug, javascript

#2396 Fix `startsWith()` call in update-release condition
  .github/workflows/deploy-production.yml
Labels: bug, github

#2399 fix: ensure organizations tab is only viewed for usdr admins
  packages/client/src/components/Layout.vue
Labels: bug, javascript

#2388 feat: update preferences link in emails to point to the new profile page
  packages/server/src/lib/email.js
  terraform/main.tf
  terraform/modules/gost_api/task.tf
  terraform/modules/gost_api/variables.tf
  terraform/prod.tfvars
  terraform/sandbox.tfvars
  terraform/staging.tfvars
  terraform/variables.tf
Labels: enhancement, Infra, terraform, javascript

#2405 Adjust RUM sample rates in Production
  terraform/prod.tfvars
Labels: Infra, terraform

#2397 Document troubleshooting information for releases
  docs/releasing.md
Labels: documentation

#2394 feat: remove "Occasional Updates" toggle from profile page
  packages/client/src/components/EmailSettingsBanner.vue
  packages/client/src/components/Modals/ProfileSettings.vue
  packages/client/src/store/modules/users.js
  packages/client/src/views/MyProfile.vue
Labels: enhancement, javascript
