Repository usdigitalresponse/usdr-gost, pull requests merged in 2023-03, with the labels that each got.

#1038 Configure terraform for production environment
  terraform/production.s3.tfbackend
  terraform/production.tfvars
Labels: Infra

#1072 RELEASE: Send emails from grants-notifications@website_domain (#1063)
  terraform/main.tf
Labels: Infra

#1125 Fix: #877 Coalesce to no-op statement for dynamic execute query
  packages/server/migrations/20230219162719_migrate_varchar_columns_to_text.js
Labels: bug

#1148 Hide multiselect labels on grants table and grant details
  docker/README.md
  docs/setup-mac.md
  packages/client/src/components/GrantsTable.vue
  packages/client/src/components/Modals/GrantDetails.vue
Labels: bug, ux goodness

#1155 Improvements to Docker documentation
  docker/README.md
Labels: documentation
