Repository usdigitalresponse/usdr-gost, pull requests merged in 2024-10, with the labels that each got.

#3532 Feature: Grant Notes feed #3428
  packages/client/src/components/CopyButton.vue
  packages/client/src/components/GrantActivity.vue
  packages/client/src/components/GrantNote.spec.js
  packages/client/src/components/GrantNote.vue
  packages/client/src/components/GrantNotes.spec.js
  packages/client/src/components/GrantNotes.vue
  packages/client/src/components/Modals/GrantFollowers.spec.js
  packages/client/src/components/Modals/GrantFollowers.vue
  packages/client/src/components/UserHeaderText.spec.js
  packages/client/src/components/UserHeaderText.vue
  packages/client/src/helpers/featureFlags/index.js
  packages/client/src/helpers/fetchApi.js
  packages/client/src/helpers/testHelpers.js
  packages/client/src/scss/custom.scss
  packages/client/src/store/modules/grants.js
  packages/client/src/views/GrantDetailsView.vue
  packages/client/vitest.setup.ts
  packages/server/__tests__/api/grants.test.js
  packages/server/__tests__/lib/grants-collaboration.test.js
  packages/server/package.json
  packages/server/src/lib/grantsCollaboration/followers.js
  packages/server/src/lib/grantsCollaboration/notes.js
  packages/server/src/routes/grants.js
  yarn.lock
Labels: enhancement, dependencies, javascript

#3563 Update output file version to 2024-10-01
  packages/server/src/arpa_reporter/data/treasury/project111210BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project18_229233BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project19_234BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project211214BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project2128BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project215218BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project224227BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project236BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project31BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project32BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project4142BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project51518BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project519521BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/projectBaselineBulkUploadTemplate.xlsx
  packages/server/src/arpa_reporter/lib/outputTemplates.json
Labels: javascript

#3582 Feature: Grant Activity digest notification preference
  packages/client/src/views/MyProfileView.spec.js
  packages/client/src/views/MyProfileView.vue
  packages/server/migrations/20241004230649_add_grant_activity_to_email_subscriptions_notification_type.js
  packages/server/src/lib/email/constants.js
Labels: enhancement, javascript, database-changes

#3606 fix: 3570 - feature flag in front of grant activity preference
  packages/client/src/views/MyProfileView.spec.js
  packages/client/src/views/MyProfileView.vue
Labels: bug, enhancement, Grant Finder, javascript

#3623 chore: bump up the container memory and cpu temporarily to handle large volume of requests
  terraform/modules/gost_api/task.tf
Labels: Infra, terraform

#3624 Add tracing instrumentation for ARPA `POST /api/uploads` handler
  packages/server/src/arpa_reporter/services/persist-upload.js
  packages/server/src/lib/access-helpers.js
Labels: arpa quarterly reporter, javascript

#3625 Enable container runtime metrics
  terraform/main.tf
  terraform/prod.tfvars
  terraform/staging.tfvars
  terraform/variables.tf
Labels: Infra, terraform

#3605 Chore: Minor doc update for local dev and staging deployment
  docs/releasing.md
  usdr-gost.code-workspace
Labels: documentation, Grant Finder, skip-changelog

#3604 feat(grants): login screen - update registration section text and links
  packages/client/src/views/LoginView.spec.js
  packages/client/src/views/LoginView.vue
Labels: enhancement, javascript

#3614 Bug: refine data fetching flow
  packages/client/src/components/GrantActivity.vue
  packages/client/src/store/modules/grants.js
Labels: bug, javascript

#3569 Feature: Adjust display for share grant events
  packages/client/src/components/GrantActivity.vue
  packages/client/src/components/GrantNote.spec.js
  packages/client/src/components/GrantNotes.spec.js
  packages/client/src/components/GrantNotes.vue
  packages/client/src/components/Modals/GrantFollowers.vue
  packages/client/src/components/ShareGrant.vue
  packages/client/src/components/UserActivityItem.spec.js
  packages/client/src/components/UserActivityItem.vue
  packages/client/src/views/GrantDetailsView.vue
  packages/server/src/db/index.js
Labels: enhancement, javascript

#3269 Add forecasted columns to grants table
  packages/server/migrations/20240902220727_add_forecasted_columns_to_grants.js
Labels: javascript, database-changes

#3649 fix: ensure picklist values are formatted correctly prior to comparison
  packages/server/src/arpa_reporter/services/validate-upload.js
Labels: bug, javascript

#3593 feat: Migrate grants_interested data to grant_followers and update PUT handler
  packages/server/__tests__/api/grants.test.js
  packages/server/migrations/20241008000515_migrate_grants_interested.js
  packages/server/src/routes/grants.js
Labels: enhancement, javascript, database-changes

#3592 Feat: Add Edit/Delete dropdown
  packages/client/src/components/GrantNotes.spec.js
  packages/client/src/components/GrantNotes.vue
  packages/client/src/store/modules/grants.js
  packages/server/__tests__/api/grants.test.js
  packages/server/__tests__/lib/grants-collaboration.test.js
  packages/server/knexfile.js
  packages/server/migrations/20241004230649_add_grant_activity_to_email_subscriptions_notification_type.js
  packages/server/migrations/20241011165653_cascade-delete-grant-notes.js
  packages/server/src/lib/grantsCollaboration/index.js
  packages/server/src/lib/grantsCollaboration/notes.js
  packages/server/src/routes/grants.js
Labels: enhancement, javascript, database-changes

#3652 Add pino logging
  packages/server/__tests__/lib/access-helpers.test.js
  packages/server/package.json
  packages/server/src/arpa_reporter/configure.js
  packages/server/src/arpa_reporter/lib/audit-report.js
  packages/server/src/arpa_reporter/services/generate-arpa-report.js
  packages/server/src/configure.js
  packages/server/src/lib/access-helpers.js
  packages/server/src/lib/logging.js
  yarn.lock
Labels: enhancement, dependencies, javascript
