Repository usdigitalresponse/usdr-gost, pull requests merged in 2024-08, with the labels that each got.

#3294 feat(grants-collaboration): create library
  packages/server/__tests__/lib/access-helpers.test.js
  packages/server/__tests__/lib/grants-collaboration.test.js
  packages/server/__tests__/lib/test-global-setup.js
  packages/server/package.json
  packages/server/src/lib/grantsCollaboration/index.js
  packages/server/src/lib/grantsCollaboration/notes.js
Labels: enhancement, javascript

#3336 feat(grants-collaboration): migration for grant_followers table
  packages/server/migrations/20240804181729_create_grant_followers.js
Labels: enhancement, javascript, database-changes

#3337 feat(grants-collaboration): create follow/unfollow funcs
  packages/server/__tests__/lib/grants-collaboration.test.js
  packages/server/src/lib/grantsCollaboration/followers.js
  packages/server/src/lib/grantsCollaboration/index.js
Labels: enhancement, javascript

#3280 New Card Container Design
  packages/client/src/views/GrantDetailsView.vue
Labels: javascript

#3371 Update ARPA input template to v20240702
  packages/server/src/arpa_reporter/data/ARPA SFRF Reporting Workbook v20240702.xlsm
  packages/server/src/arpa_reporter/environment.js
  packages/server/src/arpa_reporter/lib/templateDropdowns.json
  packages/server/src/arpa_reporter/lib/templateRules.json
  packages/server/src/scripts/generateRules.mjs
Labels: javascript

#3317 Adding service, env, version tags to email
  packages/server/__tests__/email/email.test.js
  packages/server/src/lib/email.js
Labels: javascript

#3387 Pipeline
  terraform/datadog_email_activity.tf
Labels: Infra, terraform

#3410 Adding trace ids to email tags
  packages/server/src/lib/email.js
Labels: javascript

#3398 fix: support validation of projects with ec code 7.3
  packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js
  packages/server/src/arpa_reporter/lib/arpa-ec-codes.js
  packages/server/src/arpa_reporter/services/generate-arpa-report.js
  packages/server/src/arpa_reporter/services/validate-upload.js
Labels: bug, javascript

#3415 Fix: Invalid `target_format` in SES logs-to-metrics pipeline
  terraform/datadog_email_activity.tf
  terraform/staging.tfvars
  terraform/variables.tf
Labels: bug, documentation, Infra, terraform

#3417 Fix: Invalid `target_format` in SES logs-to-metrics pipeline (again)
  terraform/datadog_email_activity.tf
Labels: bug, Infra, terraform, skip-changelog

#3345 feat(grants-collaboration): API endpoints for grant notes creation
  packages/server/__tests__/api/grants.test.js
  packages/server/src/routes/grants.js
Labels: enhancement, Grant Finder, javascript

#3418 Fix: Typo in `trace_id_remapper.sources` list
  terraform/datadog_email_activity.tf
Labels: bug, Infra, terraform, skip-changelog

#3419 Fix: Pipeline filter query
  terraform/datadog_email_activity.tf
Labels: bug, Infra, terraform, skip-changelog

#3395 feat(grants-collaboration): expose notes retrieval
  packages/server/__tests__/api/grants.test.js
  packages/server/seeds/dev/01_main.js
  packages/server/src/db/index.js
  packages/server/src/routes/grants.js
Labels: enhancement, javascript

#3432 Add unified service tags to email metrics generated from logs
  terraform/datadog_email_activity.tf
Labels: Infra, terraform, metrics, skip-changelog

#3396 feat(grants-collaboration): expose unfollow for grant
  packages/server/__tests__/api/grants.test.js
  packages/server/src/routes/grants.js
Labels: enhancement, javascript

#3408 Bug fix for disabled button
  packages/client/src/views/GrantDetailsView.vue
Labels: bug, javascript

#3397 feat(grants-collaboration): expose follow for grant
  packages/server/__tests__/api/grants.test.js
  packages/server/src/routes/grants.js
Labels: enhancement, javascript

#3427 feat(grants-collaboration): retrieve follower for grant
  packages/server/__tests__/api/grants.test.js
  packages/server/__tests__/lib/grants-collaboration.test.js
  packages/server/__tests__/lib/test-global-setup.js
  packages/server/src/lib/grantsCollaboration/followers.js
  packages/server/src/lib/grantsCollaboration/index.js
  packages/server/src/routes/grants.js
Labels: enhancement, javascript

#3441 chore: update input template (v20240823)
  packages/server/src/arpa_reporter/data/ARPA SFRF Reporting Workbook v20240823.xlsm
  packages/server/src/arpa_reporter/environment.js
  packages/server/src/arpa_reporter/lib/templateDropdowns.json
  packages/server/src/arpa_reporter/lib/templateRules.json
Labels: javascript

#3433 chore: update export templates (v2024-08)
  packages/server/src/arpa_reporter/data/treasury/expendituresLT50000BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/subawardBulkUpload.xlsx
  packages/server/src/arpa_reporter/lib/outputTemplates.json
  packages/server/src/scripts/parseOutputTemplates.mjs
Labels: javascript
