Repository usdigitalresponse/usdr-gost, pull requests merged in 2024-05, with the labels that each got.

#3010 audit report: source project metadata from most recent record
  packages/server/src/arpa_reporter/lib/audit-report.js
Labels: javascript

#3026 Trim `Client website bundle` release artifact
  .github/workflows/deploy-production.yml
Labels: bug, github

#2981 2980 create new quarterly GitHub issue template
  .github/ISSUE_TEMPLATE/arpa_quarterly_checklist.yml
Labels: github

#2974 Send emails via SES using a configuration set.
  packages/server/__tests__/email/email.test.js
  packages/server/src/lib/gost-aws.js
  terraform/email.tf
  terraform/prod.tfvars
  terraform/sandbox.tfvars
  terraform/staging.tfvars
  terraform/variables.tf
Labels: Infra, terraform, javascript

#3035 Stop setting configuration set when sending emails.
  packages/server/__tests__/email/email.test.js
  packages/server/src/lib/gost-aws.js
Labels: bug, javascript

#2975 Add vite decision doc
  docs/decisions/0008-migrate-to-vite.md
Labels: documentation

#3048 Remove dead dashboard code
  packages/client/src/store/index.js
  packages/client/src/store/modules/dashboard.js
  packages/server/__tests__/db/db.test.js
  packages/server/src/configure.js
  packages/server/src/db/index.js
  packages/server/src/routes/dashboard.js
Labels: javascript

#3027 Fix overlooked audit_report.generate callsite
  packages/server/src/arpa_reporter/routes/audit-report.js
Labels: bug, arpa quarterly reporter, arpa audit report, javascript

#3051 Ensure add form modals reset when re-opened
  packages/client/src/components/Modals/AddOrganization.vue
  packages/client/src/components/Modals/AddTeam.vue
  packages/client/src/components/Modals/AddUser.vue
Labels: javascript

#3011 Configure the click tracking subdomain to support https.
  packages/server/__tests__/email/email.test.js
  packages/server/src/lib/gost-aws.js
  terraform/email.tf
  terraform/main.tf
  terraform/staging.tfvars
Labels: Infra, terraform, javascript

#3079 Colocate client tests with the files under test
  packages/client/src/arpa_reporter/components/PageNavigation.spec.js
  packages/client/src/arpa_reporter/helpers/form-helpers.spec.js
  packages/client/src/arpa_reporter/views/AgenciesView.spec.js
  packages/client/src/arpa_reporter/views/HomeView.spec.js
  packages/client/src/arpa_reporter/views/UploadView.spec.js
  packages/client/src/arpa_reporter/views/UploadsView.spec.js
  packages/client/src/arpa_reporter/views/User.spec.js
  packages/client/src/components/BaseLayout.spec.js
  packages/client/src/components/Modals/AddOrganization.spec.js
  packages/client/src/components/Modals/AddTeam.spec.js
  packages/client/src/components/Modals/EditOrganization.spec.js
  packages/client/src/components/Modals/EditTeam.spec.js
  packages/client/src/helpers/currency.spec.js
  packages/client/src/helpers/dates.spec.js
  packages/client/src/helpers/featureFlags/index.spec.js
  packages/client/src/helpers/fetchApi.spec.js
  packages/client/src/helpers/gtag.spec.js
  packages/client/src/router/index.spec.js
  packages/client/src/views/DashboardView.spec.js
  packages/client/src/views/OrganizationsView.spec.js
  packages/client/src/views/TeamsView.spec.js
  packages/client/tests/unit/arpa_reporter/server/lib/format.spec.js
  packages/server/__tests__/arpa_reporter/server/lib/format.spec.js
Labels: javascript

#3080 Fix: Allow `SendEmail` using configuration set
  terraform/modules/gost_api/email.tf
Labels: bug, Infra, terraform

#3050 Fix markGrantAsViewed bug
  packages/server/__tests__/db/db.test.js
  packages/server/migrations/20240430210546_grants_viewed_unique_add_user_id.js
  packages/server/src/db/index.js
Labels: bug, javascript, database-changes

#3089 Fix vitest warnings
  packages/client/.eslintrc.cjs
  packages/client/babel.config.cjs
  packages/client/package.json
  packages/client/vite.config.js
  packages/client/vue.config.cjs
  yarn.lock
Labels: bug, dependencies, javascript

#3104 Fix vue-select component registration
  packages/client/src/main.js
Labels: bug, javascript

#3108 Fix email sending for assign grant action
  packages/client/src/store/modules/grants.js
  packages/client/src/views/GrantDetailsView.vue
  packages/server/__tests__/api/grants.test.js
  packages/server/src/routes/grants.js
Labels: bug, javascript
