Repository usdigitalresponse/usdr-gost, pull requests merged in 2024-02, with the labels that each got.

#2548 Update nv.gov emails to prevent accidental external emails being sent
  packages/server/__tests__/api/agencies.test.js
  packages/server/__tests__/api/grants.test.js
  packages/server/__tests__/api/grantsSavedSearch.test.js
  packages/server/__tests__/api/keywords.test.js
  packages/server/seeds/dev/ref/users.js
Labels: javascript

#2539 Upgrade GHA usages of actions/upload-artifact and actions/download-artifact
  .github/workflows/build.yml
  .github/workflows/deploy-production.yml
  .github/workflows/terraform-apply.yml
  .github/workflows/terraform-plan.yml
Labels: github

#2540 Clarify local development login flow
  docker/README.md
  docs/setup-gmail.md
  packages/server/__tests__/api/agencies.test.js
  packages/server/__tests__/api/users.test.js
  packages/server/seeds/dev/ref/users.js
  packages/server/src/lib/email.js
Labels: documentation, Infra, javascript

#2568 Use copy icon from design
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2529 feat: add ability to notify users on report failure
  packages/server/__tests__/email/email.test.js
  packages/server/src/arpa_reporter/lib/audit-report.js
  packages/server/src/arpa_reporter/services/generate-arpa-report.js
  packages/server/src/lib/email.js
  packages/server/src/lib/email/email-nodemailer.js
  packages/server/src/lib/gost-aws.js
Labels: enhancement, javascript

#2576 Grant details page design updates
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2588 chore: turn on category of funding activity field in production
  terraform/prod.tfvars
Labels: enhancement, Infra, terraform

#2586 Full implementation of print and copy actions on Grant Details page
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2579 Fix up Category of Funding Activity label and add colons to table
  packages/client/src/views/GrantDetails.vue
Labels: bug, javascript

#2578 Clicking top level nav bar items from grant details page doesn't work
  packages/client/src/components/Layout.vue
Labels: javascript

#2602 Adjust size and style of Grant Details buttons
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2612 updating left and right margins and right column width
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2596 feat: Add github-actions ecosystem to dependabot
  .github/dependabot.yml
Labels: enhancement, github

#2538 Remove README badges
  README.md
Labels: bug, documentation, github

#2620 2569 dropdown display for assign grant and team status
  packages/client/src/assets/adjust-vue-select.css
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2646 [issue-2585] Make Grants tab the default tab
  packages/client/src/components/Layout.vue
  packages/client/src/router/index.js
Labels: bug, javascript

#2648 Grant details close date explanation, step 1
  packages/server/migrations/20240221163647_add_close_date_explanation.js
Labels: javascript, database-changes

#2638 fix: #1801 - closed period reporting
  packages/client/src/arpa_reporter/views/Home.vue
  packages/client/src/assets/adjust-vue-select.css
  packages/client/tests/unit/arpa_reporter/views/Home.spec.js
  packages/server/__tests__/arpa_reporter/server/routes/audit_report.spec.js
  packages/server/src/arpa_reporter/db/reporting-periods.js
  packages/server/src/arpa_reporter/lib/audit-report.js
  packages/server/src/arpa_reporter/routes/audit-report.js
  packages/server/src/arpa_reporter/routes/exports.js
  packages/server/src/arpa_reporter/services/records.js
Labels: bug, javascript

#2651 Grant details close date explanation, step 2
  packages/server/__tests__/lib/grants-ingest.test.js
  packages/server/src/lib/grants-ingest.js
Labels: javascript

#2652 Grant details close date explanation, step 3
  packages/server/migrations/20240221164356_populate_close_date_explanation.js
Labels: javascript, database-changes

#2653 Grant details close date explanation, step 4
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2656 Make it easier to enable Postgres persistence in dev.
  .gitignore
  docker/README.md
Labels: documentation, Infra, github

#2667 Remove the feature flag 'categoryOfFundingActivitySearchFieldEnabled'.
  packages/client/public/deploy-config.js
  packages/client/src/components/Modals/GrantDetailsLegacy.vue
  packages/client/src/components/Modals/SearchPanel.vue
  packages/client/src/helpers/featureFlags/index.js
  terraform/prod.tfvars
  terraform/sandbox.tfvars
  terraform/staging.tfvars
Labels: enhancement, Infra, terraform, javascript

#2674 Flip grant detail page flag on in development
  packages/client/public/deploy-config.js
Labels: javascript

#2688 Align eslint rules across environments
  packages/client/.eslintrc.js
Labels: javascript

#2666 [Decision] Adopt vue/recommended linting
  docs/decisions/0007-adopt-vue-recommended-linting.md
Labels: documentation

#2676 Update grant details page overall layout
  packages/client/src/views/GrantDetails.vue
Labels: javascript
