Repository usdigitalresponse/usdr-gost, pull requests merged in 2024-01, with the labels that each got.

#2430 fix: ensure we ignore microsoft safe links requests
  packages/server/__tests__/lib/access-helpers.test.js
  packages/server/__tests__/lib/grants-ingest.test.js
  packages/server/src/lib/access-helpers.js
  packages/server/src/routes/sessions.js
Labels: bug, javascript

#2432 fix: release naming issue
  .github/release-drafter.yml
Labels: bug, github

#2433 fix: make name explicit to 2024
  .github/release-drafter.yml
Labels: bug, github

#2436 Update release-drafter config
  .github/release-drafter.yml
Labels: bug, github

#2439 chore: turn on myProfile feature
  terraform/prod.tfvars
Labels: Infra, terraform

#2435 Add jsonb column to store raw body in grants table
  packages/server/migrations/20240105223338_add_raw_body_jsonb_column_to_grants.js
  packages/server/seeds/dev/01_main.js
  packages/server/seeds/dev/ref/grants.js
Labels: javascript, database-changes

#2442 chore: add logging around safe links requests
  packages/server/src/lib/access-helpers.js
Labels: javascript

#2448 Set time-of-day for Dependabot schedules
  .github/dependabot.yml
Labels: enhancement, github

#2463 Fix deployed version of deploy-config.js.
  packages/client/public/index.html
  terraform/modules/gost_website/tpl/deploy-config.js
Labels: bug, Infra, terraform, javascript

#2464 Add click action event "grant search result" to grant rows
  packages/client/src/components/GrantsTable.vue
  packages/server/.env.example
Labels: javascript

#2461 Add job to refresh AWS credentials before TF apply
  .github/workflows/deploy-production.yml
Labels: github

#2469 fix: correct typo in EC1.4
  packages/server/src/arpa_reporter/lib/arpa-ec-codes.js
Labels: bug, javascript

#2164 Support archiving subrecipients
  packages/client/src/arpa_reporter/views/Subrecipients.vue
  packages/server/__tests__/arpa_reporter/server/lib/audit-report.spec.js
  packages/server/migrations/20240118000244_add_subrecipients_archived_col.js
  packages/server/src/arpa_reporter/db/arpa-subrecipients.js
  packages/server/src/arpa_reporter/routes/subrecipients.js
Labels: javascript, database-changes

#2471 Clean up leftover console.log statement
  packages/client/src/arpa_reporter/views/Subrecipients.vue
Labels: javascript

#2479 Adding RUM instrumentation to grant details modal UI elements
  packages/client/src/components/Modals/GrantDetailsLegacy.vue
Labels: javascript

#2487 Updating GrantDetails.vue with RUM Instrumentation
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2486 Add user story template
  .github/ISSUE_TEMPLATE/user_story.yml
Labels: skip-changelog, github

#2478 Add .gitattributes file for this repo
  packages/.gitattributes
Labels: javascript, skip-changelog

#2467 feat: add user_id and user_properties to GA events
  packages/client/src/helpers/gtag.js
  packages/client/src/main.js
  packages/client/tests/unit/helpers/gtag.spec.js
Labels: enhancement, javascript

#2490 ARPA subrecipients — invert null check typo
  packages/server/src/arpa_reporter/db/arpa-subrecipients.js
Labels: arpa quarterly reporter, javascript

#2499 fix: #2105 - audit report enhancements
  packages/server/src/arpa_reporter/lib/audit-report.js
  packages/server/src/arpa_reporter/services/records.js
Labels: bug, javascript

#2492 Adding New User Information for RUM Instrumentation
  packages/client/src/main.js
Labels: javascript

#2507 Add pdf to list of binary file types in .gitattributes.
  packages/.gitattributes
Labels: javascript

#2454 Populate funding_activity_category_codes for all grants
  packages/client/src/components/GrantsTable.vue
  packages/server/__tests__/api/grants.test.js
  packages/server/__tests__/db/seeds/fixtures.js
  packages/server/__tests__/lib/grants-ingest.test.js
  packages/server/migrations/20240119190230_set_raw_body_json_from_raw_body_again.js
  packages/server/migrations/20240119214120_populate_funding_activity_category_codes_column.js
  packages/server/seeds/dev/ref/grants.js
  packages/server/src/lib/grants-ingest.js
  packages/server/src/lib/grantscraper/index.js
  packages/server/src/routes/grants.js
  terraform/sandbox.tfvars
  terraform/staging.tfvars
Labels: Infra, terraform, javascript, database-changes

#2514 Output template updates 2024-01
  packages/server/src/arpa_reporter/data/treasury/project111210BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project18_229233BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project19_234BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project211214BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project2128BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project215218BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project224227BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project236BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project31BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project32BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project4142BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project51518BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project519521BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/projectBaselineBulkUploadTemplate.xlsx
  packages/server/src/arpa_reporter/lib/outputTemplates.json
Labels: javascript

#2509 2370 Move existing grant details content to match new placement
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2517 Add UTM tags to Grant Email URLs
  packages/server/src/lib/email.js
  packages/server/src/static/email_templates/_grant_detail.html
  packages/server/src/static/email_templates/base.html
Labels: javascript

#2515 Exclude .xlsx and .xlsm files from line ending autofixes
  .gitattributes
Labels: javascript

#2530 chore: add latest templates
  packages/server/src/arpa_reporter/data/treasury/TaxOffsetRevIncCoveredChanges.xlsx
  packages/server/src/arpa_reporter/data/treasury/TaxOffsetRevRedCoveredChanges.xlsx
  packages/server/src/arpa_reporter/data/treasury/TaxOffsetSpendingCuts.xlsx
  packages/server/src/arpa_reporter/data/treasury/project111210BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project18_229233BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project19_234BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project211214BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project2128BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project215218BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project224227BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project236BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project31BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project32BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project4142BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project51518BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project519521BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/projectBaselineBulkUploadTemplate.xlsx
  packages/server/src/arpa_reporter/data/treasury/slfrfBroadbandLocationBulkUpload.xlsx
Labels: javascript

#2532 Only .gitignore the root data folder in the server package
  packages/server/.gitignore
Labels: javascript, github

#2547 Add app global context
  packages/client/src/arpa_reporter/main.js
  packages/client/src/main.js
Labels: javascript

#2549 fix: grants.gov url change
  packages/client/src/components/Modals/GrantDetailsLegacy.vue
  packages/client/src/views/GrantDetails.vue
  packages/server/src/lib/email.js
  packages/server/src/routes/grants.js
Labels: bug, javascript
