Repository usdigitalresponse/usdr-gost, pull requests merged in 2024-03, with the labels that each got.

#2689 Add email user link to grant detail page
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2690 Add user avatar to grant details page
  packages/client/src/components/Layout.vue
  packages/client/src/components/Modals/EditUser.vue
  packages/client/src/components/UserAvatar.vue
  packages/client/src/helpers/constants.js
  packages/client/src/views/GrantDetails.vue
  packages/client/src/views/MyProfile.vue
  packages/server/src/db/index.js
Labels: javascript

#2704 Update setup-gmail.md to make docker rebuild explicit
  docs/setup-gmail.md
Labels: documentation

#2720 Stop returning the raw_body field of a grant as part of the /grants/next response.
  packages/server/src/db/index.js
Labels: javascript

#2706 Delete code for obsolete SPOC PDF feature.
  packages/client/src/components/Modals/GrantDetailsLegacy.vue
  packages/client/src/store/modules/grants.js
  packages/client/src/views/GrantDetails.vue
  packages/server/src/db/index.js
  packages/server/src/routes/grants.js
Labels: enhancement, javascript

#2710 [issue-2369] Back or Browse Grants Link from Grant Details
  packages/client/src/views/GrantDetails.vue
Labels: enhancement, javascript

#2707 Add GA4 property configuration for non-Production environments
  packages/client/public/deploy-config.js
  packages/client/src/helpers/gtag.js
  packages/client/tests/unit/helpers/gtag.spec.js
  terraform/prod.tfvars
  terraform/staging.tfvars
Labels: enhancement, Grant Finder, Infra, terraform, javascript

#2687 Refactor and fix bugs in Recent Activity and Upcoming Closing Dates tables.
  packages/client/package.json
  packages/client/src/components/ActivityTable.vue
  packages/client/src/components/ClosingDatesTable.vue
  packages/client/src/components/GrantsTable.vue
  packages/client/src/helpers/constants.js
  packages/client/src/helpers/dates.js
  packages/client/src/store/modules/grants.js
  packages/client/src/views/Dashboard.vue
  packages/client/src/views/RecentActivity.vue
  packages/client/src/views/UpcomingClosingDates.vue
  packages/client/tests/unit/helpers/dates.spec.js
  packages/client/tests/unit/views/Dashboard.spec.js
  packages/server/__tests__/db/seeds/fixtures.js
  packages/server/src/db/index.js
  packages/server/src/routes/grants.js
  yarn.lock
Labels: bug, dependencies, javascript

#2733 Fix some styles and correct back text
  packages/client/src/views/GrantDetails.vue
Labels: bug, javascript

#2694 Mark ADR 0007 "Adopt vue/recommended linting" as accepted
  docs/decisions/0007-adopt-vue-recommended-linting.md
Labels: documentation

#2654 Update eslint config with vue/recommended plugin
  packages/client/.eslintrc.js
Labels: javascript

#2677 Fix tflint warnings
  .github/workflows/qa.yml
  terraform/main.tf
  terraform/modules/gost_api/autoscaling.tf
  terraform/modules/gost_api/ecs_exec.tf
  terraform/modules/gost_api/gateway.tf
  terraform/modules/gost_api/logs.tf
  terraform/modules/gost_api/main.tf
  terraform/modules/gost_api/outputs.tf
  terraform/modules/gost_api/scraper.tf
  terraform/modules/gost_api/secrets.tf
  terraform/modules/gost_api/service.tf
  terraform/modules/gost_api/task.tf
  terraform/modules/gost_consume_grants/main.tf
  terraform/modules/gost_networking/main.tf
  terraform/modules/gost_postgres/main.tf
  terraform/modules/gost_website/cdn.tf
  terraform/modules/gost_website/main.tf
  terraform/modules/gost_website/storage.tf
  terraform/modules/gost_website/variables.tf
  terraform/modules/scheduled_ecs_task/main.tf
  terraform/modules/scheduled_ecs_task/outputs.tf
  terraform/modules/scheduled_ecs_task/variables.tf
  terraform/modules/sqs_consumer_task/compute.tf
  terraform/modules/sqs_consumer_task/main.tf
  terraform/variables.tf
Labels: bug, Infra, terraform, github

#2705 Update emails to point to new Grant Details page
  packages/server/__tests__/email/email.test.js
  packages/server/src/lib/email.js
  packages/server/src/static/email_templates/_grant_detail.html
  terraform/prod.tfvars
  terraform/staging.tfvars
Labels: Infra, terraform, javascript

#2731 Fix for visual artifact on My Grants status tabs
  packages/client/src/views/MyGrants.vue
Labels: bug, javascript

#2751 Flag DB migrations in release notes
  .github/release-drafter.yml
Labels: enhancement, skip-changelog, github

#2732 Update Grant Detail page url
  packages/client/src/router/index.js
  packages/client/src/views/Dashboard.vue
  packages/client/src/views/RecentActivity.vue
  packages/client/src/views/UpcomingClosingDates.vue
Labels: javascript

#2750 Drop the column grants.raw_body.
  packages/server/migrations/20240308203616_drop_grants_raw_body_column.js
Labels: javascript, database-changes

#2725 Fix for grant assign email with missing description
  packages/server/__tests__/db/seeds/fixtures.js
  packages/server/__tests__/email/email.test.js
  packages/server/src/lib/email.js
  packages/server/src/routes/grants.js
Labels: bug, javascript

#2734 Formatting fixes to Grant Details page
  packages/client/src/components/GrantsTable.vue
  packages/client/src/helpers/currency.js
  packages/client/src/views/GrantDetails.vue
  packages/client/tests/unit/helpers/currency.spec.js
Labels: bug, javascript

#2735 Prevent cursor from remaining in v-select component after selection
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2736 Change back link text from `Back to Results` to `Back`
  packages/client/src/App.vue
  packages/client/src/components/SearchFilter.vue
  packages/client/src/scss/colors-base-tokens.scss
  packages/client/src/scss/colors-semantic-tokens.scss
  packages/client/src/scss/custom.scss
  packages/client/src/scss/fonts.scss
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2790 Revert "fix: #1801 - revert frontend change"
  packages/client/src/arpa_reporter/views/Home.vue
  packages/client/src/assets/adjust-vue-select.css
  packages/client/tests/unit/arpa_reporter/views/Home.spec.js
Labels: bug, javascript

#2781 fix: #2609 - audit report subaward
  packages/server/src/arpa_reporter/lib/audit-report.js
  packages/server/src/arpa_reporter/services/records.js
Labels: bug, javascript

#2756 Enforce eslint plugin:vue/recommended linting and reorganize ignore list
  .github/workflows/qa.yml
  packages/client/.eslintrc.js
Labels: javascript, github

#2777 Grant Details page instrumentation
  packages/client/src/helpers/gtag.js
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2779 Flip new grant details page on in staging
  terraform/staging.tfvars
Labels: Infra, terraform

#2810 [Cleanup] Adopt eslint vue/recommended: Grant Finder: grants tables
  packages/client/.eslintrc.js
  packages/client/src/components/GrantsTable.vue
  packages/client/src/router/index.js
  packages/client/src/views/GrantsView.vue
  packages/client/src/views/MyGrantsView.vue
Labels: javascript

#2826 fix: #2609 - audit subaward fixes
  packages/server/__tests__/arpa_reporter/server/lib/audit-report.spec.js
  packages/server/src/arpa_reporter/lib/audit-report.js
Labels: bug, javascript

#2792 Grant digest email adjustments
  packages/server/__tests__/email/email.test.js
  packages/server/src/lib/email.js
  packages/server/src/lib/email/email-nodemailer.js
  packages/server/src/routes/agencies.js
  packages/server/src/static/email_templates/base.html
Labels: javascript

#2813 [Cleanup] Adopt eslint vue/recommended: Grant Finder: core views
  packages/client/.eslintrc.js
  packages/client/src/router/index.js
  packages/client/src/views/Home.vue
  packages/client/src/views/LoginView.vue
  packages/client/src/views/NotFound.vue
  packages/client/src/views/NotFoundView.vue
Labels: javascript

#2811 [Cleanup] Adopt eslint vue/recommended: Grant Finder: app files
  packages/client/.eslintrc.js
  packages/client/src/App.vue
  packages/client/src/components/BaseLayout.vue
  packages/client/src/components/Layout.vue
  packages/client/src/main.js
  packages/client/src/router/index.js
  packages/client/tests/unit/components/BaseLayout.spec.js
Labels: javascript

#2845 [Cleanup] Adopt eslint vue/recommended: Grant Finder: organizations
  packages/client/.eslintrc.js
  packages/client/src/components/Modals/AddOrganization.vue
  packages/client/src/components/Modals/EditOrganization.vue
  packages/client/src/router/index.js
  packages/client/src/views/OrganizationsView.vue
  packages/client/tests/unit/views/OrganizationsView.spec.js
Labels: javascript

#2837 Fix for email notification settings link
  packages/server/src/lib/email.js
  packages/server/src/static/email_templates/base.html
Labels: bug, javascript

#2831 Grant Details page copy email component for copying email address
  packages/client/src/components/CopyButton.vue
  packages/client/src/views/GrantDetails.vue
Labels: javascript

#2830 Update Node from v16 to v20.
  .nvmrc
  NODE_UPGRADES.md
  docker/Dockerfile
  docker/production-api.Dockerfile
  docs/setup-mac.md
  package.json
  packages/client/package.json
  packages/client/tests/unit/arpa_reporter/helpers/form-helpers.spec.js
  packages/e2e/package.json
  packages/server/package.json
  yarn.lock
Labels: documentation, dependencies, Infra, javascript

#2846 [Cleanup] Adopt eslint vue/recommended: ARPA Reporter: app files
  packages/client/.eslintrc.js
  packages/client/src/arpa_reporter/App.vue
  packages/client/src/arpa_reporter/components/PageNavigation.vue
  packages/client/tests/unit/arpa_reporter/components/PageNavigation.spec.js
Labels: javascript

#2847 [Cleanup] Adopt eslint vue/recommended: ARPA Reporter: home/login/validation views
  packages/client/.eslintrc.js
  packages/client/src/arpa_reporter/router/index.js
  packages/client/src/arpa_reporter/views/HomeView.vue
  packages/client/src/arpa_reporter/views/LoginView.vue
  packages/client/src/arpa_reporter/views/ValidationView.vue
  packages/client/tests/unit/arpa_reporter/views/HomeView.spec.js
Labels: javascript

#2863 Adjust Datadog RUM sampling in Staging
  terraform/staging.tfvars
Labels: Infra, terraform

#2849 fix: #2754 - N/A in Template Rules
  packages/server/src/arpa_reporter/lib/templateRules.json
Labels: bug, javascript

#2856 Grant Details page copy email component style tweaks
  packages/client/src/components/CopyButton.vue
Labels: javascript

#2858 Turn on grant details page in production
  terraform/prod.tfvars
  terraform/sandbox.tfvars
Labels: Infra, terraform

#2859 Turns on grant detail digest email links in production
  terraform/prod.tfvars
Labels: Infra, terraform

#2865 [Cleanup] Adopt eslint vue/recommended: Remove obsolete Vue components
  packages/client/.eslintrc.js
  packages/client/src/views/EligibilityCodes.vue
  packages/client/src/views/Keywords.vue
Labels: enhancement, Grant Finder, javascript

#2866 [Cleanup] Adopt eslint vue/recommended: Grant Finder: profile
  packages/client/.eslintrc.js
  packages/client/src/components/Modals/ProfileSettings.vue
  packages/client/src/components/UserAvatar.vue
  packages/client/src/views/MyProfile.vue
Labels: enhancement, Grant Finder, javascript

#2848 [Cleanup] Adopt eslint vue/recommended: ARPA Reporter: agency views
  packages/client/.eslintrc.js
  packages/client/src/arpa_reporter/router/index.js
  packages/client/src/arpa_reporter/views/AgenciesView.vue
  packages/client/src/arpa_reporter/views/AgencyView.vue
  packages/client/tests/unit/arpa_reporter/views/AgenciesView.spec.js
Labels: javascript

#2867 [Cleanup] Adopt eslint vue/recommended: ARPA Reporter: basic components
  packages/client/.eslintrc.js
  packages/client/src/arpa_reporter/components/AlertBox.vue
  packages/client/src/arpa_reporter/components/DownloadButton.vue
  packages/client/src/arpa_reporter/components/DownloadFileButton.vue
  packages/client/src/arpa_reporter/components/DownloadFileButtonSmall.vue
  packages/client/src/arpa_reporter/components/DownloadTemplateBtn.vue
  packages/client/src/arpa_reporter/components/StandardForm.vue
Labels: javascript

#2870 [Cleanup] Adopt eslint vue/recommended: Grant Finder: grant details
  packages/client/.eslintrc.js
  packages/client/src/components/Modals/GrantDetailsLegacy.vue
  packages/client/src/router/index.js
  packages/client/src/views/GrantDetailsView.vue
Labels: javascript

#2878 [Cleanup] Adopt eslint vue/recommended: Grant Finder: teams
  packages/client/.eslintrc.js
  packages/client/src/components/Modals/AddTeam.vue
  packages/client/src/components/Modals/EditTeam.vue
  packages/client/src/components/Modals/ImportTeams.vue
  packages/client/src/components/Modals/ImportUsers.vue
  packages/client/src/components/RecordUploader.vue
  packages/client/src/router/index.js
  packages/client/src/views/TeamsView.vue
  packages/client/tests/unit/views/TeamsView.spec.js
Labels: Grant Finder, javascript

#2868 [Cleanup] Adopt eslint vue/recommended: ARPA Reporter: subrecipient views
  packages/client/.eslintrc.js
  packages/client/src/arpa_reporter/router/index.js
  packages/client/src/arpa_reporter/views/SubrecipientView.vue
  packages/client/src/arpa_reporter/views/SubrecipientsView.vue
Labels: performance reporter, javascript

#2869 [Cleanup] Adopt eslint vue/recommended: ARPA Reporter: user views
  packages/client/.eslintrc.js
  packages/client/src/arpa_reporter/router/index.js
  packages/client/src/arpa_reporter/views/UserView.vue
  packages/client/src/arpa_reporter/views/UsersView.vue
  packages/client/tests/unit/arpa_reporter/views/User.spec.js
Labels: performance reporter, javascript
