Repository usdigitalresponse/usdr-gost, pull requests merged in 2024-09, with the labels that each got.

#3446 feat(grants collaboration) - retrieve grant followers
  packages/server/__tests__/api/grants.test.js
  packages/server/__tests__/lib/grants-collaboration.test.js
  packages/server/src/lib/grantsCollaboration/followers.js
  packages/server/src/lib/grantsCollaboration/index.js
  packages/server/src/routes/grants.js
Labels: enhancement, javascript

#3440 feat: Add client-side feature flag for Follow+Notes functionality
  packages/client/public/deploy-config.js
  packages/client/src/helpers/featureFlags/index.js
  terraform/prod.tfvars
  terraform/staging.tfvars
Labels: enhancement, Infra, terraform, javascript

#3439 feat: UI Tweaks to Card Design in Grant Detail
  packages/client/src/views/GrantDetailsView.vue
Labels: enhancement, javascript

#3480 Fix `FromAsCasing` build check error
  docker/production-api.Dockerfile
Labels: bug, Infra, skip-changelog

#3470 feat(notes+follow) - grant activity card
  packages/client/src/components/BaseLayout.vue
  packages/client/src/components/GrantActivity.spec.js
  packages/client/src/components/GrantActivity.vue
  packages/client/src/components/ShareGrant.spec.js
  packages/client/src/components/ShareGrant.vue
  packages/client/src/helpers/dates.js
  packages/client/src/helpers/fetchApi.js
  packages/client/src/store/modules/grants.js
  packages/client/src/views/GrantDetailsView.vue
Labels: enhancement, javascript

#3490 Bug fix: replace computed flag
  packages/client/src/components/GrantActivity.vue
Labels: bug, enhancement, javascript

#3497 Fix: invalid API Gateway access log vars
  terraform/modules/gost_api/gateway.tf
Labels: bug, Infra, terraform, skip-changelog

#3479 Vue3 for tests
  packages/client/src/arpa_reporter/views/HomeView.spec.js
  packages/client/src/arpa_reporter/views/NewUploadView.spec.js
  packages/client/src/arpa_reporter/views/UserView.spec.js
  packages/client/src/components/BaseLayout.spec.js
  packages/client/vite.config.js
  packages/client/vitest.setup.ts
Labels: javascript

#3503 feat: update logic to reflect July 2024 IAA and Beneficiary changes
  packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js
  packages/server/src/arpa_reporter/services/validate-upload.js
Labels: enhancement, javascript

#3513 Bug fix: My Grants showing all grants
  packages/client/src/router/index.js
  packages/client/src/store/modules/grants.js
  packages/client/src/views/GrantDetailsView.spec.js
  packages/client/src/views/GrantDetailsView.vue
Labels: bug, javascript

#3519 feat(notes+follow) - Share Grant card
  packages/client/src/views/GrantDetailsView.vue
Labels: enhancement, javascript

#3505 Feature: Grant followers modal
  packages/client/src/components/CopyButton.vue
  packages/client/src/components/GrantActivity.vue
  packages/client/src/components/Modals/GrantFollowers.spec.js
  packages/client/src/components/Modals/GrantFollowers.vue
  packages/client/vitest.setup.ts
  packages/server/__tests__/api/utils.js
  packages/server/__tests__/lib/grants-collaboration.test.js
  packages/server/src/lib/grantsCollaboration/followers.js
Labels: enhancement, Grant Finder, javascript

#3522 3372 - adds database changes to support managing IAA subrecipients
  packages/server/__tests__/arpa_reporter/server/db/arpa-subrecipients.spec.js
  packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js
  packages/server/migrations/20240918183745_drop_constraints_to_arpa_subrecipients.js
  packages/server/migrations/20240918183915_add_name_to_arpa_subrecipients.js
  packages/server/src/arpa_reporter/db/arpa-subrecipients.js
  packages/server/src/arpa_reporter/services/validate-upload.js
Labels: javascript, database-changes

#3528 Cleanup for email scripts
  packages/server/src/scripts/sendGrantDigest.mjs
  packages/server/src/scripts/sendGrantDigestEmail.js
Labels: bug, Grant Finder, javascript

#3471 feat: add API to retrieve grant notes for specific user via Finder API
  packages/server/__tests__/lib/grants-collaboration.test.js
  packages/server/src/lib/grantsCollaboration/index.js
  packages/server/src/lib/grantsCollaboration/notes.js
  packages/server/src/routes/grants.js
Labels: enhancement, javascript

#3553 Fix: unit tests for db module
  packages/server/__tests__/db/db.test.js
  packages/server/__tests__/db/seeds/fixtures.js
  packages/server/src/db/index.js
Labels: bug, javascript
