Repository usdigitalresponse/usdr-gost, pull requests merged in 2024-04, with the labels that each got.

#2883 fix: validations report correct row number when blank rows are present
  packages/server/src/arpa_reporter/services/records.js
  packages/server/src/arpa_reporter/services/validate-upload.js
Labels: bug, javascript

#2892 [Cleanup] Adopt eslint vue/recommended: Grant Finder: search modals
  packages/client/.eslintrc.js
  packages/client/src/components/Modals/AddKeyword.vue
  packages/client/src/components/Modals/SavedSearchPanel.vue
  packages/client/src/components/Modals/SearchPanel.vue
  packages/client/src/components/SearchFilter.vue
  packages/client/src/store/index.js
  packages/client/src/store/modules/keywords.js
Labels: javascript

#2896 Fix agency loading for Grant Details page
  packages/client/src/views/GrantDetailsView.vue
Labels: bug, javascript

#2888 [Cleanup] Adopt eslint vue/recommended: Grant Finder: users
  packages/client/.eslintrc.js
  packages/client/src/components/Modals/AddUser.vue
  packages/client/src/components/Modals/EditUser.vue
  packages/client/src/components/Modals/ImportTeams.vue
  packages/client/src/components/Modals/ImportUsers.vue
  packages/client/src/router/index.js
  packages/client/src/views/UsersView.vue
Labels: Grant Finder, javascript

#2838 Command to send debug emails, and documentation of email development workflow
  docs/development.md
  docs/img/setup-email-ethereal-inbox.png
  docs/img/setup-email-ethereal-welcome.png
  docs/img/setup-email-ethereal.png
  docs/img/setup-email-smtp-configuration.png
  docs/setup-email.md
  docs/setup-gmail.md
  docs/setup-mac.md
  packages/server/.env.example
  packages/server/package.json
  packages/server/src/lib/email.js
  packages/server/src/lib/email/email-nodemailer.js
  packages/server/src/scripts/sendDebugEmail.js
Labels: documentation, Grant Finder, javascript

#2887 [Cleanup] Adopt eslint vue/recommended: ARPA Reporter: reporting period views
  packages/client/.eslintrc.js
  packages/client/src/arpa_reporter/views/ReportingPeriod.vue
  packages/client/src/arpa_reporter/views/ReportingPeriods.vue
Labels: javascript

#2885 [Cleanup] Adopt eslint vue/recommended: ARPA Reporter: upload views
  packages/client/.eslintrc.js
  packages/client/src/arpa_reporter/router/index.js
  packages/client/src/arpa_reporter/views/UploadView.vue
  packages/client/src/arpa_reporter/views/UploadsView.vue
  packages/client/tests/unit/arpa_reporter/views/UploadView.spec.js
  packages/client/tests/unit/arpa_reporter/views/UploadsView.spec.js
Labels: javascript

#2893 Adds mailpit to docker-compose for email capture
  .gitignore
  docker-compose.yml
  docs/img/setup-email-ethereal-inbox.png
  docs/img/setup-email-ethereal-welcome.png
  docs/img/setup-email-ethereal.png
  docs/img/setup-email-mailpit-inbox.png
  docs/img/setup-email-mailpit-message.png
  docs/img/setup-email-send-debug-email.png
  docs/img/setup-email-send-debug-received.png
  docs/img/setup-email-smtp-configuration.png
  docs/setup-email.md
  packages/server/.env.example
Labels: documentation, Infra, javascript, github

#2889 [Cleanup] Adopt eslint vue/recommended: Grant Finder: dashboard
  packages/client/.eslintrc.js
  packages/client/src/components/ActivityTable.vue
  packages/client/src/components/ClosingDatesTable.vue
  packages/client/src/router/index.js
  packages/client/src/views/DashboardView.vue
  packages/client/src/views/RecentActivityView.vue
  packages/client/src/views/UpcomingClosingDatesView.vue
  packages/client/tests/unit/views/DashboardView.spec.js
Labels: Grant Finder, javascript

#2904 Output template updates 2024-04
  packages/server/src/arpa_reporter/data/treasury/project111210BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project18_229233BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project19_234BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project211214BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project2128BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project215218BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project224227BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project236BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project31BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project32BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project4142BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project51518BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project519521BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/projectBaselineBulkUploadTemplate.xlsx
  packages/server/src/arpa_reporter/data/treasury/subRecipientBulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/subawardBulkUpload.xlsx
  packages/server/src/arpa_reporter/lib/outputTemplates.json
Labels: javascript

#2884 [Cleanup] Adopt eslint vue/recommended: ARPA Reporter: new views
  packages/client/.eslintrc.js
  packages/client/src/arpa_reporter/views/NewTemplate.vue
  packages/client/src/arpa_reporter/views/NewUpload.vue
Labels: javascript

#2886 [Cleanup] Adopt eslint vue/recommended: ARPA Reporter: annual performance reporter
  packages/client/.eslintrc.js
  packages/client/src/views/ArpaAnnualPerformanceReporter.vue
Labels: javascript

#2917 fix: #2753 - Audit Report Round to 2 Decimal Places
  packages/server/src/arpa_reporter/lib/audit-report.js
  packages/server/src/arpa_reporter/lib/format.js
Labels: bug, javascript

#2921 Input template 2024 04 04
  packages/server/src/arpa_reporter/data/ARPA SFRF Reporting Workbook v20240404.xlsm
  packages/server/src/arpa_reporter/environment.js
  packages/server/src/arpa_reporter/lib/templateDropdowns.json
  packages/server/src/arpa_reporter/lib/templateRules.json
Labels: arpa quarterly reporter, javascript

#2923 Write new columns to treasury export templates
  packages/server/src/arpa_reporter/services/generate-arpa-report.js
Labels: javascript

#2931 chore: enables new email ecs container in production
  terraform/prod.tfvars
Labels: Infra, terraform

#2946 Delete code for the old grants digest.
  packages/server/__tests__/api/agencies.test.js
  packages/server/__tests__/db/db.test.js
  packages/server/__tests__/email/email.test.js
  packages/server/__tests__/scripts/sendGrantDigestEmail.test.js
  packages/server/src/db/index.js
  packages/server/src/index.js
  packages/server/src/lib/email.js
  packages/server/src/routes/agencies.js
  packages/server/src/scripts/sendGrantDigestEmail.js
  terraform/main.tf
  terraform/modules/gost_api/task.tf
  terraform/modules/gost_api/variables.tf
  terraform/modules/gost_consume_grants/compute.tf
  terraform/modules/sqs_consumer_task/compute.tf
  terraform/prod.tfvars
  terraform/sandbox.tfvars
  terraform/staging.tfvars
  terraform/variables.tf
Labels: Infra, terraform, javascript

#2947 fix: #2944 - updated contractor uei validation
  packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js
  packages/server/src/arpa_reporter/services/validate-upload.js
Labels: bug, javascript

#2954 Clean up myProfileEnabled flag.
  packages/client/public/deploy-config.js
  packages/client/src/assets/usdr_logo_white_wide.svg
  packages/client/src/components/BaseLayout.vue
  packages/client/src/components/Modals/ProfileSettings.vue
  packages/client/src/helpers/featureFlags/index.js
  packages/client/src/router/index.js
  packages/client/tests/unit/components/BaseLayout.spec.js
  packages/server/src/db/index.js
  terraform/prod.tfvars
  terraform/sandbox.tfvars
  terraform/staging.tfvars
Labels: Infra, terraform, javascript

#2934 Remove plugin:vue/recommended overrides setup from .eslintrc.js
  packages/client/.eslintrc.js
Labels: javascript

#2940 Fix email "from name" via AWS SES and standardize names
  packages/server/__tests__/email/email.test.js
  packages/server/src/lib/email.js
  packages/server/src/lib/gost-aws.js
Labels: bug, javascript

#2945 Tweak Terraform code to work when run against blank environment.
  terraform/main.tf
  terraform/modules/gost_api/ecs_exec.tf
  terraform/modules/gost_api/email.tf
  terraform/modules/gost_api/logs.tf
  terraform/modules/gost_api/postgres.tf
  terraform/modules/gost_api/secrets.tf
  terraform/modules/gost_api/storage.tf
  terraform/modules/gost_website/storage.tf
Labels: Infra, terraform

#2958 Delete backend ENABLE_MY_PROFILE feature flag.
  packages/server/src/lib/email.js
  terraform/main.tf
  terraform/modules/gost_api/task.tf
  terraform/modules/gost_api/variables.tf
  terraform/prod.tfvars
  terraform/sandbox.tfvars
  terraform/staging.tfvars
  terraform/variables.tf
Labels: enhancement, Infra, terraform, javascript

#2933 Clean up View naming conventions after eslint vue recommended migration
  packages/client/src/arpa_reporter/router/index.js
  packages/client/src/arpa_reporter/views/NewTemplateView.vue
  packages/client/src/arpa_reporter/views/NewUploadView.vue
  packages/client/src/arpa_reporter/views/ReportingPeriodView.vue
  packages/client/src/arpa_reporter/views/ReportingPeriodsView.vue
  packages/client/src/router/index.js
  packages/client/src/views/ArpaAnnualPerformanceReporterView.vue
  packages/client/src/views/MyProfileView.vue
Labels: javascript

#2924 Define Terraform infrastructure for email metrics
  terraform/email.tf
  terraform/main.tf
  terraform/modules/gost_api/task.tf
  terraform/modules/gost_api/variables.tf
  terraform/prod.tfvars
  terraform/staging.tfvars
  terraform/variables.tf
Labels: Infra, terraform, javascript

#2966 Summarize `terraform plan` in CI/CD
  .github/workflows/ci.yml
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
  .github/workflows/publish-terraform-plan.yml
  .github/workflows/terraform-plan.yml
Labels: terraform, github

#2969 Complete switchover to `@` import alias
  packages/client/.eslintrc.js
  packages/client/package.json
  packages/client/src/arpa_reporter/App.vue
  packages/client/src/arpa_reporter/components/DownloadTemplateBtn.vue
  packages/client/src/arpa_reporter/components/PageNavigation.vue
  packages/client/src/arpa_reporter/main.js
  packages/client/src/arpa_reporter/scss/index.scss
  packages/client/src/arpa_reporter/store/index.js
  packages/client/src/arpa_reporter/views/AgencyView.vue
  packages/client/src/arpa_reporter/views/HomeView.vue
  packages/client/src/arpa_reporter/views/LoginView.vue
  packages/client/src/arpa_reporter/views/NewTemplateView.vue
  packages/client/src/arpa_reporter/views/NewUploadView.vue
  packages/client/src/arpa_reporter/views/ReportingPeriodView.vue
  packages/client/src/arpa_reporter/views/ReportingPeriodsView.vue
  packages/client/src/arpa_reporter/views/SubrecipientView.vue
  packages/client/src/arpa_reporter/views/SubrecipientsView.vue
  packages/client/src/arpa_reporter/views/UploadView.vue
  packages/client/src/arpa_reporter/views/UploadsView.vue
  packages/client/src/arpa_reporter/views/UserView.vue
  packages/client/src/arpa_reporter/views/UsersView.vue
  packages/client/src/arpa_reporter/views/ValidationView.vue
  packages/client/src/components/BaseLayout.vue
  packages/client/src/components/GrantsTable.vue
  packages/client/src/components/Modals/GrantDetailsLegacy.vue
  packages/client/src/helpers/featureFlags/index.js
  packages/client/src/main.js
  packages/client/src/router/index.js
  packages/client/src/store/index.js
  packages/client/tests/unit/arpa_reporter/helpers/form-helpers.spec.js
  packages/client/tests/unit/arpa_reporter/server/lib/format.spec.js
  packages/client/tests/unit/helpers/fetchApi.spec.js
  yarn.lock
Labels: dependencies, javascript

#2988 Upgrade vuelidate
  packages/client/package.json
  packages/client/src/components/Modals/AddOrganization.vue
  packages/client/src/components/Modals/AddTeam.vue
  packages/client/src/components/Modals/AddUser.vue
  packages/client/src/components/Modals/EditTeam.vue
  packages/client/src/components/Modals/EditUser.vue
  packages/client/src/components/Modals/SavedSearchPanel.vue
  packages/client/src/components/Modals/SearchPanel.vue
  packages/client/src/main.js
  packages/client/tests/unit/components/Modals/AddOrganization.spec.js
  packages/client/tests/unit/components/Modals/AddTeam.spec.js
  packages/client/tests/unit/components/Modals/EditOrganization.spec.js
  packages/client/tests/unit/components/Modals/EditTeam.spec.js
  yarn.lock
Labels: dependencies, javascript

#2989 Migrate client code entirely to ES6 import style
  packages/client/.eslintrc.js
  packages/client/babel.config.js
  packages/client/src/arpa_reporter/views/ReportingPeriodsView.vue
  packages/client/src/components/RecordUploader.vue
  packages/client/src/helpers/constants.js
  packages/client/src/helpers/fetchApi.js
  packages/client/src/main.js
  packages/client/src/mixin/resizableTable.js
  packages/client/src/store/modules/agencies.js
  packages/client/src/store/modules/dashboard.js
  packages/client/src/store/modules/grants.js
  packages/client/src/store/modules/roles.js
  packages/client/src/store/modules/tenants.js
  packages/client/src/store/modules/users.js
  packages/client/vue.config.js
Labels: javascript

#2990 Replace lodash-checkit usage with vuelidate
  packages/client/package.json
  packages/client/src/arpa_reporter/views/LoginView.vue
  packages/client/src/views/LoginView.vue
  yarn.lock
Labels: dependencies, javascript

#2997 Remove unused dependencies
  packages/client/package.json
  packages/server/package.json
  yarn.lock
Labels: dependencies, javascript
