Repository usdigitalresponse/usdr-gost, pull requests merged in 2024-11, with the labels that each got.

#3734 Fix: cascade delete `users` to grant notes and follows
  packages/server/migrations/20241118203005_cascade-delete-grant-notes-for-user.js
  packages/server/migrations/20241118203302_cascade-delete-followed-grants-for-user.js
Labels: bug, javascript, database-changes

#3634 chore(grants): add eslint-plugin-vuejs-accessibility and disable errors flagged
  docs/decisions/0010-include-eslint-plugin-vuejs-accessibility.md
  packages/client/.eslintrc.cjs
  packages/client/package.json
  packages/client/src/arpa_reporter/components/PageNavigation.vue
  packages/client/src/arpa_reporter/components/StandardForm.vue
  packages/client/src/arpa_reporter/views/LoginView.vue
  packages/client/src/arpa_reporter/views/UploadsView.vue
  packages/client/src/arpa_reporter/views/ValidationView.vue
  packages/client/src/components/CopyButton.vue
  packages/client/src/components/GrantsTable.vue
  packages/client/src/components/Modals/AddTeam.vue
  packages/client/src/components/Modals/EditOrganization.vue
  packages/client/src/components/Modals/EditTeam.vue
  packages/client/src/components/Modals/EditUser.vue
  packages/client/src/views/ArpaAnnualPerformanceReporterView.vue
  packages/client/src/views/GrantDetailsView.vue
  packages/client/src/views/LoginView.vue
  yarn.lock
Labels: documentation, dependencies, javascript

#3633 feat: 3601 - Follow/Notes updates to My Grants
  packages/client/src/components/GrantsTable.spec.js
  packages/client/src/components/GrantsTable.vue
  packages/client/src/router/index.js
  packages/client/src/views/MyGrantsView.spec.js
  packages/client/src/views/MyGrantsView.vue
  packages/server/.env.example
  packages/server/__tests__/api/grants.test.js
  packages/server/src/db/constants.js
  packages/server/src/db/index.js
  packages/server/src/routes/grants.js
Labels: enhancement, javascript

#3754 fix(grants): check for null data and feature flag
  packages/client/src/components/GrantsTable.vue
Labels: bug, enhancement, javascript

#3766 Reduce automation noise
  .github/dependabot.yml
  .github/workflows/code-scanning.yml
Labels: skip-changelog, github
