Repository usdigitalresponse/usdr-gost, pull requests merged in 2024-06, with the labels that each got.

#3081 Fix: Missing `terraform validate` output from `stderr` in CI status reports
  .github/workflows/terraform-plan.yml
Labels: bug, Infra, terraform, github

#3109 fix: #2987 - removed unnecessary validation
  packages/server/src/arpa_reporter/services/validate-upload.js
Labels: bug, javascript

#3116 fix: project summaries v2 tab pulls metadata from last *EC* record
  packages/server/src/arpa_reporter/lib/audit-report.js
Labels: bug, javascript

#3134 fix: ensure uploads are sorted when fetched from DB
  packages/server/src/arpa_reporter/db/uploads.js
Labels: bug, javascript

#3147 Adding share feature flag
  packages/client/public/deploy-config.js
  packages/client/src/helpers/featureFlags/index.js
  packages/server/.env.example
  terraform/prod.tfvars
  terraform/staging.tfvars
Labels: enhancement, Infra, terraform, javascript

#3152 Fix failing `dependency-review-action` jobs
  .github/workflows/code-scanning.yml
Labels: bug, dependencies, github

#3095 Migrate vue-cli to vite
  package.json
  packages/client/.eslintrc.cjs
  packages/client/arpa_reporter/index.html
  packages/client/arpa_reporter/main.js
  packages/client/babel.config.cjs
  packages/client/index.html
  packages/client/jsconfig.json
  packages/client/main.js
  packages/client/package.json
  packages/client/src/arpa_reporter/router/index.js
  packages/client/src/arpa_reporter/views/LoginView.vue
  packages/client/src/components/GrantsTable.vue
  packages/client/src/components/Modals/SearchPanel.vue
  packages/client/src/router/index.js
  packages/client/src/store/index.js
  packages/client/src/views/GrantDetailsView.vue
  packages/client/src/views/LoginView.vue
  packages/client/vite.config.js
  packages/client/vue.config.cjs
  yarn.lock
Labels: dependencies, javascript

#3151 Update deprecated Vue slot syntax
  packages/client/src/arpa_reporter/views/SubrecipientsView.vue
  packages/client/src/arpa_reporter/views/UploadsView.vue
  packages/client/src/arpa_reporter/views/UsersView.vue
  packages/client/src/arpa_reporter/views/ValidationView.vue
  packages/client/src/components/Modals/AddTeam.vue
  packages/client/src/components/Modals/EditOrganization.vue
  packages/client/src/components/Modals/EditTeam.vue
Labels: javascript

#3159 Mark vite decision as accepted
  docs/decisions/0008-migrate-to-vite.md
Labels: documentation

#3173 Tech debt: Remove dead code for Grants.gov scraper
  packages/server/src/configure.js
  packages/server/src/index.js
  packages/server/src/lib/cron.js
  packages/server/src/lib/grantscraper/index.js
  packages/server/src/lib/grantsgov.js
  packages/server/src/routes/refresh.js
  terraform/main.tf
  terraform/modules/gost_api/scraper.tf
  terraform/modules/gost_api/task.tf
  terraform/modules/gost_api/variables.tf
  terraform/modules/gost_consume_grants/compute.tf
  terraform/modules/sqs_consumer_task/compute.tf
  terraform/prod.tfvars
  terraform/sandbox.tfvars
  terraform/staging.tfvars
  terraform/variables.tf
Labels: Infra, terraform, javascript

#3162 feat: update email preferences copy
  packages/client/src/views/MyProfileView.spec.js
  packages/client/src/views/MyProfileView.vue
Labels: enhancement, javascript

#3163 Disable click tracking for magic links
  packages/server/src/lib/email.js
Labels: javascript

#3188 Deploy client-side `shareTerminologyEnabled` feature flag
  terraform/prod.tfvars
  terraform/staging.tfvars
Labels: enhancement, Infra, terraform

#3164 Add assigned by user details to grants assigned to agencies endpoint
  packages/server/__tests__/api/grants.test.js
  packages/server/seeds/dev/ref/grants.js
  packages/server/seeds/dev/ref/users.js
  packages/server/src/db/index.js
Labels: javascript

#3160 Adding share terminology to the My Grants view
  packages/client/src/router/index.js
  packages/client/src/views/MyGrantsView.vue
Labels: javascript

#3183 Update Recent Activity CSV Export File
  packages/server/__tests__/api/grants.test.js
  packages/server/src/routes/grants.js
Labels: javascript

#3175 Include assignee name in Recent Activity view
  packages/client/src/components/ActivityTable.spec.js
  packages/client/src/components/ActivityTable.vue
  packages/server/__tests__/db/db.test.js
  packages/server/src/db/index.js
Labels: javascript

#3184 Grant Details Page - move grants.gov, copy, print buttons
  packages/client/src/views/GrantDetailsView.vue
Labels: javascript
