Repository usdigitalresponse/usdr-gost, pull requests merged in 2024-07, with the labels that each got.

#3209 Issue #3200 Add grant_notes and grant_notes_revisions table migration
  packages/server/migrations/20240622205204_add-grant-notes-table.js
Labels: javascript, database-changes

#3192 Assign-to-Share: Update email templates
  packages/server/__tests__/email/email.test.js
  packages/server/src/lib/email.js
  packages/server/src/static/email_templates/_grant_assigned_body.html
Labels: javascript

#3208 Assign-to-share: Update grant detail page
  packages/client/src/views/GrantDetailsView.vue
Labels: javascript

#3226 chore: update export templates (v2024-07)
  packages/server/src/arpa_reporter/data/treasury/project111210BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project18_229233BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project19_234BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project211214BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project2128BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project215218BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project224227BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project236BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project31BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project32BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project4142BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project51518BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project519521BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/projectBaselineBulkUploadTemplate.xlsx
  packages/server/src/arpa_reporter/data/treasury/subRecipientBulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/subawardBulkUpload.xlsx
  packages/server/src/arpa_reporter/lib/outputTemplates.json
Labels: arpa quarterly reporter, arpa output templates, javascript

#3232 bump: terraform version from 13.8 to 13.13
  terraform/modules/gost_postgres/main.tf
Labels: Infra, terraform

#3191 [Decision Discussion] Migrate to Vue 3
  docs/decisions/0009-upgrade-to-vue-3.md
Labels: documentation

#3257 Mark vue 3 decision accepted
  docs/decisions/0009-upgrade-to-vue-3.md
Labels: documentation

#3258 Add "renders" tests for all Vue components
  packages/client/src/arpa_reporter/components/AlertBox.spec.js
  packages/client/src/arpa_reporter/components/DownloadButton.spec.js
  packages/client/src/arpa_reporter/components/DownloadFileButton.spec.js
  packages/client/src/arpa_reporter/components/DownloadFileButtonSmall.spec.js
  packages/client/src/arpa_reporter/components/DownloadTemplateBtn.spec.js
  packages/client/src/arpa_reporter/components/StandardForm.spec.js
  packages/client/src/arpa_reporter/views/AgenciesView.spec.js
  packages/client/src/arpa_reporter/views/AgencyView.spec.js
  packages/client/src/arpa_reporter/views/LoginView.spec.js
  packages/client/src/arpa_reporter/views/NewTemplateView.spec.js
  packages/client/src/arpa_reporter/views/NewUploadView.spec.js
  packages/client/src/arpa_reporter/views/ReportingPeriodView.spec.js
  packages/client/src/arpa_reporter/views/ReportingPeriodsView.spec.js
  packages/client/src/arpa_reporter/views/SubrecipientView.spec.js
  packages/client/src/arpa_reporter/views/SubrecipientsView.spec.js
  packages/client/src/arpa_reporter/views/UploadView.spec.js
  packages/client/src/arpa_reporter/views/UploadsView.spec.js
  packages/client/src/arpa_reporter/views/UserView.spec.js
  packages/client/src/arpa_reporter/views/UsersView.spec.js
  packages/client/src/arpa_reporter/views/ValidationView.spec.js
  packages/client/src/components/BaseLayout.spec.js
  packages/client/src/components/ClosingDatesTable.spec.js
  packages/client/src/components/CopyButton.spec.js
  packages/client/src/components/GrantsTable.spec.js
  packages/client/src/components/Modals/AddUser.spec.js
  packages/client/src/components/Modals/EditOrganization.spec.js
  packages/client/src/components/Modals/EditUser.spec.js
  packages/client/src/components/Modals/ImportTeams.spec.js
  packages/client/src/components/Modals/ImportUsers.spec.js
  packages/client/src/components/Modals/SavedSearchPanel.spec.js
  packages/client/src/components/Modals/SearchPanel.spec.js
  packages/client/src/components/RecordUploader.spec.js
  packages/client/src/components/SearchFilter.spec.js
  packages/client/src/components/UserAvatar.spec.js
  packages/client/src/helpers/featureFlags/index.spec.js
  packages/client/src/helpers/gtag.spec.js
  packages/client/src/views/ArpaAnnualPerformanceReporterView.spec.js
  packages/client/src/views/DashboardView.spec.js
  packages/client/src/views/GrantDetailsView.spec.js
  packages/client/src/views/GrantsView.spec.js
  packages/client/src/views/LoginView.spec.js
  packages/client/src/views/MyGrantsView.spec.js
  packages/client/src/views/MyProfileView.spec.js
  packages/client/src/views/NotFoundView.spec.js
  packages/client/src/views/OrganizationsView.spec.js
  packages/client/src/views/OrganizationsView.vue
  packages/client/src/views/RecentActivityView.spec.js
  packages/client/src/views/UpcomingClosingDatesView.spec.js
  packages/client/src/views/UsersView.spec.js
Labels: javascript

#3268 chore(Assign-to-Share): flip prod ff
  terraform/prod.tfvars
Labels: Infra, terraform

#3273 Upgrade RDS CA bundle
  .github/CODEOWNERS
  .github/release-drafter.yml
  packages/server/rds-combined-ca-bundle.pem
  packages/server/rds-global-bundle.pem
  terraform/modules/gost_api/task.tf
  terraform/modules/gost_consume_grants/compute.tf
  terraform/modules/sqs_consumer_task/compute.tf
Labels: enhancement, Infra, terraform, javascript, database-changes, github

#3296 Fix issue with double-submission of new search
  packages/client/src/components/Modals/SearchPanel.vue
Labels: bug, javascript

#3286 Upgrade RDS certificate on Staging
  terraform/main.tf
  terraform/modules/gost_postgres/main.tf
  terraform/modules/gost_postgres/variables.tf
  terraform/prod.tfvars
  terraform/sandbox.tfvars
  terraform/staging.tfvars
  terraform/variables.tf
Labels: enhancement, Infra, terraform

#3309 Upgrade RDS certificate on Production
  terraform/prod.tfvars
  terraform/variables.tf
Labels: enhancement, Infra, terraform
