Repository usdigitalresponse/usdr-gost, pull requests merged in 2024-12, with the labels that each got.

#3632 Add ECS health checks for API tasks
  packages/server/__tests__/api/health.test.js
  packages/server/src/routes/health.js
  packages/server/src/scripts/healthcheck.js
  terraform/modules/gost_api/task.tf
Labels: enhancement, Infra, terraform, javascript

#3793 chore(arpa_reporting): make quarterly drop down keyboard navigable
  packages/client/src/arpa_reporter/components/PageNavigation.vue
Labels: javascript, accessibility

#3794 chore(gost): update vitest version and add testing-library for accessible queries
  docs/decisions/0011-use-testing-library-vue.md
  packages/client/package.json
  packages/client/src/arpa_reporter/views/HomeView.spec.js
  packages/client/vitest.setup.ts
  yarn.lock
Labels: documentation, dependencies, javascript

#3818 Address outdated package.json files
  package.json
  packages/server/package.json
Labels: javascript
