Repository usdigitalresponse/usdr-gost, pull requests merged in 2025-01, with the labels that each got.

#3845 Chore - Update output templates for Q4-2024
  packages/server/src/arpa_reporter/data/treasury/project111210BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project18_229233BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project19_234BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project211214BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project2128BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project215218BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project224227BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project236BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project31BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project32BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project4142BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project51518BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/project519521BulkUpload.xlsx
  packages/server/src/arpa_reporter/data/treasury/projectBaselineBulkUploadTemplate.xlsx
  packages/server/src/arpa_reporter/lib/outputTemplates.json
Labels: javascript

#3838 chore(arpa_reporter): remove ValidationView and references
  packages/client/src/arpa_reporter/components/PageNavigation.vue
  packages/client/src/arpa_reporter/router/index.js
  packages/client/src/arpa_reporter/views/ValidationView.spec.js
  packages/client/src/arpa_reporter/views/ValidationView.vue
Labels: javascript

#3851 3802 - Ensure evidence based total spend value is derived from the most recent upload
  packages/server/__tests__/arpa_reporter/server/lib/audit-report.spec.js
  packages/server/src/arpa_reporter/lib/audit-report.js
Labels: javascript

#3857 Guard inclusion of `grant.followed_by_agencies` array data during CSV generation
  packages/server/src/routes/grants.js
Labels: bug, javascript

#3863 fix: ensure there is guard clause to catch issues when projects are missing EC records
  packages/server/src/arpa_reporter/lib/audit-report.js
Labels: bug, javascript

#3914 fix: ensure all the fields of subawardBulkUpload.csv are being populated
  packages/server/src/arpa_reporter/services/generate-arpa-report.js
Labels: bug, javascript

#3915 feat: add tests for subwardBulkUpload export file generation
  packages/server/__tests__/arpa_reporter/server/services/generate-arpa-report.spec.js
  packages/server/src/arpa_reporter/services/generate-arpa-report.js
Labels: enhancement, javascript

#3935 fix: add missing fields into the baseline report
  packages/server/__tests__/arpa_reporter/server/services/generate-arpa-report.spec.js
  packages/server/src/arpa_reporter/services/generate-arpa-report.js
Labels: bug, javascript
